
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jefry Hernandez
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_lamias = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sp_lamias = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        js_aletalamia = new javax.swing.JSpinner();
        jp_Hamadriades = new javax.swing.JPanel();
        jp_silfides = new javax.swing.JPanel();
        js_silfides = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jp_salamandra = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        sp_salamandra = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        cb_hadas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_nombre = new javax.swing.JTextField();
        js_altura = new javax.swing.JSpinner();
        js_edad = new javax.swing.JSpinner();
        jl_salud = new javax.swing.JLabel();
        jl_poder = new javax.swing.JLabel();
        jif_hada = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jLabel9.setText("Branquias");

        sp_lamias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));

        jLabel7.setText("Aletas");

        js_aletalamia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));

        javax.swing.GroupLayout jp_lamiasLayout = new javax.swing.GroupLayout(jp_lamias);
        jp_lamias.setLayout(jp_lamiasLayout);
        jp_lamiasLayout.setHorizontalGroup(
            jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_lamiasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp_lamias)
                    .addComponent(js_aletalamia))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jp_lamiasLayout.setVerticalGroup(
            jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_lamiasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_lamias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_lamiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(js_aletalamia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp_HamadriadesLayout = new javax.swing.GroupLayout(jp_Hamadriades);
        jp_Hamadriades.setLayout(jp_HamadriadesLayout);
        jp_HamadriadesLayout.setHorizontalGroup(
            jp_HamadriadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );
        jp_HamadriadesLayout.setVerticalGroup(
            jp_HamadriadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        js_silfides.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));

        jLabel10.setText("Alas");

        javax.swing.GroupLayout jp_silfidesLayout = new javax.swing.GroupLayout(jp_silfides);
        jp_silfides.setLayout(jp_silfidesLayout);
        jp_silfidesLayout.setHorizontalGroup(
            jp_silfidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_silfidesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(js_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jp_silfidesLayout.setVerticalGroup(
            jp_silfidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_silfidesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jp_silfidesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(js_silfides, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel11.setText("Alas");

        sp_salamandra.setModel(new javax.swing.SpinnerNumberModel(16, 16, null, 1));

        javax.swing.GroupLayout jp_salamandraLayout = new javax.swing.GroupLayout(jp_salamandra);
        jp_salamandra.setLayout(jp_salamandraLayout);
        jp_salamandraLayout.setHorizontalGroup(
            jp_salamandraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salamandraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(65, 65, 65)
                .addComponent(sp_salamandra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jp_salamandraLayout.setVerticalGroup(
            jp_salamandraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_salamandraLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp_salamandraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sp_salamandra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Creacion de Hadas");

        cb_hadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lamias", "Hamadriades", "Silfides", "Salamandras" }));
        cb_hadas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_hadasItemStateChanged(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Altura");

        jLabel4.setText("Edad");

        jLabel5.setText("Salud");

        jLabel6.setText("Poder");

        js_altura.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));

        js_edad.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jif_hada.setBorder(null);
        jif_hada.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jif_hada.setVisible(true);

        javax.swing.GroupLayout jif_hadaLayout = new javax.swing.GroupLayout(jif_hada.getContentPane());
        jif_hada.getContentPane().setLayout(jif_hadaLayout);
        jif_hadaLayout.setHorizontalGroup(
            jif_hadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );
        jif_hadaLayout.setVerticalGroup(
            jif_hadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Funciones");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar como");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("About");
        jMenu1.add(jMenuItem5);

        jMenuItem4.setText("Salir");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cb_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(js_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_edad))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jl_poder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_salud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(133, 133, 133))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jif_hada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_hadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(js_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(js_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jl_poder, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jif_hada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_hadasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_hadasItemStateChanged
        if (evt.getStateChange() == 1) {

            tipodehada = (String) cb_hadas.getSelectedItem();
            if (tipodehada.equals("Lamias")) {
                jl_salud.setText("473");
                jl_poder.setText("57");
                jif_hada.setContentPane(jp_lamias);
                jif_hada.setVisible(true);
                jif_hada.setVisible(true);

            } else if (tipodehada.equals("Hamadriades")) {
                jl_salud.setText("373");
                jl_poder.setText("78");
                jif_hada.setContentPane(jp_Hamadriades);
                jif_hada.setVisible(true);

            } else if (tipodehada.equals("Silfides")) {
                jl_salud.setText("563");
                jl_poder.setText("67");
                jif_hada.setContentPane(jp_silfides);
                jif_hada.setVisible(true);
                jif_hada.setVisible(true);
            } else if (tipodehada.equals("Salamandras")) {
                jl_salud.setText("683");
                jl_poder.setText("71");
                jif_hada.setContentPane(jp_salamandra);
                jif_hada.setVisible(true);
                jif_hada.setVisible(true);
            }
        }
    }//GEN-LAST:event_cb_hadasItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        tipodehada = (String) cb_hadas.getSelectedItem();
        if (tipodehada.equals("Lamias")) {
            String nombre = jt_nombre.getText();
            int edad = (Integer) js_edad.getValue();
            int altura = (Integer) js_altura.getValue();
            int aleta = (Integer) js_aletalamia.getValue();
            int branquia = (Integer) sp_lamias.getValue();
            double salud = 475;
            double poder = 57;
            Lamias lami = new Lamias(aleta, branquia, nombre, altura, edad, salud, poder);
            lista.add(lami);
            jt_nombre.setText("");

        } else if (tipodehada.equals("Hamadriades")) {
            //jif_hada.setContentPane();
            String nombre = jt_nombre.getText();
            int edad = (Integer) js_edad.getValue();
            int altura = (Integer) js_altura.getValue();
            double salud = 546;
            double poder = 78;
            Hamadriades hama = new Hamadriades(nombre, altura, edad, salud, poder);
            lista.add(hama);
            jt_nombre.setText("");
        } else if (tipodehada.equals("Silfides")) {
            String nombre = jt_nombre.getText();
            int edad = (Integer) js_edad.getValue();
            int altura = (Integer) js_altura.getValue();
            double salud = 563;
            double poder = 67;
            int alas = (Integer) js_silfides.getValue();
            Silfides silfi = new Silfides(alas, nombre, altura, edad, salud, poder);
            jt_nombre.setText("");
        } else if (tipodehada.equals("Salamandras")) {
            String nombre = jt_nombre.getText();
            int edad = (Integer) js_edad.getValue();
            int altura = (Integer) js_altura.getValue();
            double salud = 683;
            double poder = 71;
            int alas = (Integer) sp_salamandra.getValue();
            Salamandra sala = new Salamandra(alas, nombre, altura, edad, salud, poder);
            lista.add(sala);

            jt_nombre.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new FileNameExtensionFilter("cbm", "cbm"));
        int file = jfc.showOpenDialog(this);
        if (file == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            String path = f.getPath();
            System.out.println(path);
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo Binario", "cbm");
        jfc.addChoosableFileFilter(filtro);
        int seleccion = jfc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File fichero = null;
                System.out.println("fsa");
                if (jfc.getFileFilter().getDescription().equals("Archivo Binario")) {
                    fichero = new File(jfc.getSelectedFile().getPath() + ".cbm");
                    agregar_archivo(fichero);
                    System.out.println("fas");
                } else {
                    fichero = jfc.getSelectedFile();
                    System.out.println("afsa");
                }

            } catch (Exception e) {
                e.printStackTrace();
            } finally {

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_hadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JInternalFrame jif_hada;
    private javax.swing.JLabel jl_poder;
    private javax.swing.JLabel jl_salud;
    private javax.swing.JPanel jp_Hamadriades;
    private javax.swing.JPanel jp_lamias;
    private javax.swing.JPanel jp_salamandra;
    private javax.swing.JPanel jp_silfides;
    private javax.swing.JSpinner js_aletalamia;
    private javax.swing.JSpinner js_altura;
    private javax.swing.JSpinner js_edad;
    private javax.swing.JSpinner js_silfides;
    private javax.swing.JTextField jt_nombre;
    private javax.swing.JSpinner sp_lamias;
    private javax.swing.JSpinner sp_salamandra;
    // End of variables declaration//GEN-END:variables
    String tipodehada;
    ArrayList<Hada> lista = new ArrayList();
    File f;

    public void agregararchivo(File f1) throws IOException {
        /*FileWriter fw;
        BufferedWriter bw;
         */

        String path = f1.getPath();
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(path, false);
            bw = new ObjectOutputStream(fw);
            for (Hada us : lista) {
                bw.writeObject(us);
            }

            try {
                bw.close();
                fw.close();
            } catch (IOException e) {
            }

        } catch (IOException e) {
        }

    }

    public void cargarrarchivo(File f1) {

        String path = f1.getPath();
        try {
            lista = new ArrayList();
            Hada temp = null;
            if (f.exists()) {

                FileInputStream entrada = new FileInputStream(path);
                ObjectInputStream objeto = new ObjectInputStream(entrada);

                try {

                    while ((temp = (Hada) objeto.readObject()) != null) {
                        lista.add(temp);
                    }
                } catch (EOFException e) {
                }
                objeto.close();
                entrada.close();
            }

        } catch (IOException | ClassNotFoundException e) {

        }
    }

    public void agregar_archivo(File f) throws IOException {
        /*FileWriter fw;
        BufferedWriter bw;
         */

        f = new File(f.getPath() + ".cmb");
        FileOutputStream fw = null;
        ObjectOutputStream bw = null;
        try {
            fw = new FileOutputStream(f, true);
            bw = new ObjectOutputStream(fw);
            if (lista.size() > 0) {
                for (Hada us : lista) {
                    bw.writeObject(us);
                }
            }
            bw.flush();
            try {
                bw.close();
                fw.close();
            } catch (IOException e) {
            }

        } catch (IOException e) {
        }

    }
}
